-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["chocchip20000"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip20000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -47, 37.5  ,  -60, 22.5  ,  46, -37.5  ,  59, -23.5  ,  59, 31.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip20000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   46, -37.5  ,  -60, 22.5  ,  -60, -31.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip1"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -51, 22  ,  -54, -10  ,  46, -18  ,  51, -14  ,  46, 20  ,  9, 47  ,  -30, 42  ,  -45, 35  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   46, -18  ,  27, -40  ,  31, -42  ,  42, -32  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -22, -46  ,  -10, -49  ,  8, -47  ,  46, -18  ,  -54, -10  ,  -51, -20  ,  -40, -37  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   46, 20  ,  51, -14  ,  53, 5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   9, 47  ,  46, 20  ,  34, 39  ,  21, 47  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   46, -18  ,  8, -47  ,  27, -40  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip2"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip2", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -2, 40  ,  -32, 5  ,  -32, -14  ,  -12, -39  ,  15, -35  ,  31, 0  ,  27, 23  ,  17, 39  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip2", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -32, 5  ,  -2, 40  ,  -22, 32  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip2", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -12, -39  ,  -32, -14  ,  -25, -34  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip3"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip3", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   25, -22  ,  34, 9  ,  -18, 42  ,  -24, 30  ,  -27, 16  ,  -13, -49  ,  12, -44  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip3", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   6, 50  ,  -18, 42  ,  34, 9  ,  30, 34  ,  19, 48  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip3", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -13, -49  ,  -27, 16  ,  -33, 1  ,  -35, -25  ,  -26, -42  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip4"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip4", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -7, 56  ,  -23.5, 36.5  ,  -18, -60  ,  -17, -60  ,  12.5, -51.5  ,  26.5, -15.5  ,  36.5, 29.5  ,  20, 58  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip4", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -18, -60  ,  -23.5, 36.5  ,  -38.5, -14.5  ,  -38.5, -35.5  ,  -32.5, -50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip4", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -23.5, 36.5  ,  -7, 56  ,  -18.5, 48.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip5"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip5", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -19.5, 50.5  ,  -19.5, 40.5  ,  22, 67  ,  -4, 65  ,  -14, 60  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip5", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   14, -55  ,  24.5, -26.5  ,  38.5, 27.5  ,  38.5, 39.5  ,  28.5, 61.5  ,  -20, -70  ,  -19, -70  ,  6.5, -65.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip5", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -20, -70  ,  28.5, 61.5  ,  22, 67  ,  -19.5, 40.5  ,  -40.5, -23.5  ,  -39.5, -51.5  ,  -31, -64  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip6"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip6", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -16.5, 52  ,  23, 77.5  ,  -1, 74.5  ,  -12, 68.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip6", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -23.5, 31  ,  2.5, -75  ,  7, -70.5  ,  20.5, -36  ,  30.5, 10  ,  23, 77.5  ,  -16.5, 52  ,  -23.5, 41  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip6", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -24, -79  ,  2.5, -75  ,  -23.5, 31  ,  -44.5, -33  ,  -43.5, -61  ,  -35, -73.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip6", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   39.5, 58  ,  31, 73.5  ,  23, 77.5  ,  30.5, 10  ,  42.5, 38  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip7"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip7", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   15.5, 86.5  ,  -17.5, 43.5  ,  29.5, 4.5  ,  40.5, 27.5  ,  43.5, 41.5  ,  45.5, 56.5  ,  38.5, 74.5  ,  29.5, 85.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip7", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -17.5, 43.5  ,  15.5, 86.5  ,  -8.5, 78.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip7", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   18.5, -47.5  ,  29.5, 4.5  ,  -17.5, 43.5  ,  -23.5, 34.5  ,  -26.5, -85.5  ,  -14.5, -86.5  ,  4.5, -79.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip7", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -26.5, -85.5  ,  -23.5, 34.5  ,  -45.5, -50.5  ,  -45.5, -64.5  ,  -39.5, -77.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip8"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip8", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -20.5, 35  ,  38.5, 32  ,  46.5, 54  ,  47.5, 67  ,  38.5, 88  ,  16.5, 95  ,  -6.5, 87  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip8", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -7.5, -90  ,  9.5, -72  ,  26.5, -4  ,  -20.5, 35  ,  -48.5, -59  ,  -48.5, -73  ,  -29.5, -94  ,  -17.5, -95  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip8", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   16.5, 95  ,  38.5, 88  ,  32.5, 94  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip8", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   9.5, -72  ,  -7.5, -90  ,  -1.5, -91  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip8", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -29.5, -94  ,  -48.5, -73  ,  -39.5, -89  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip8", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -20.5, 35  ,  26.5, -4  ,  37.5, 19  ,  38.5, 32  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip8", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -48.5, -59  ,  -20.5, 35  ,  -26.5, 26  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip9"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip9", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   17, 105  ,  -3, 98  ,  -22, 25  ,  37, 22  ,  49, 64  ,  50, 79  ,  47, 88  ,  35, 105  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip9", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -9, -100  ,  -40, -34  ,  -49, -58  ,  -49, -87  ,  -41, -99  ,  -31, -104  ,  -19, -105  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip9", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -9, -100  ,  -3, -101  ,  -22, 25  ,  -28, 16  ,  -40, -34  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip9", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -22, 25  ,  25, -14  ,  36, 9  ,  37, 22  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip9", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -22, 25  ,  -3, -101  ,  14, -66  ,  25, -14  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip10"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip10", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   4.5, -65  ,  36.5, 49  ,  28.5, 64  ,  -7.5, 62  ,  -34.5, -36  ,  -34.5, -64  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip20"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip20", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   42, 38.5  ,  31, 50.5  ,  -43, -29.5  ,  -43, -48.5  ,  18, -48.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip20", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -43, -29.5  ,  31, 50.5  ,  -22, 50.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "chochip20", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   42, 38.5  ,  33, 50.5  ,  14, 50.5  ,  5, 45.5  ,  -43, -30.5  ,  -43, -48.5  ,  18, -48.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip20", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -22, 47.5  ,  -43, -30.5  ,  5, 45.5  ,  -2, 49.5  ,  -17, 50.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip30"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip30", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -58.5, -30.5  ,  -58.5, -48.5  ,  33.5, -48.5  ,  57.5, 36.5  ,  47.5, 48.5  ,  -36.5, 49.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip40"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip40", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   71.5, 35.5  ,  36, 45  ,  6.5, 44.5  ,  -73.5, -26.5  ,  -73, -48.5  ,  47, -49  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip40", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   6.5, 44.5  ,  36, 45  ,  27, 50  ,  15, 50  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip40", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   57, 50  ,  36, 45  ,  71.5, 35.5  ,  66.5, 44.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip40", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -23.5, 45.5  ,  -73.5, -26.5  ,  6.5, 44.5  ,  -3, 50  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip40", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -51, 48  ,  -73.5, -26.5  ,  -23.5, 45.5  ,  -33, 50  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip50"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip50", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   86.5, 36.5  ,  81, 45  ,  21.5, 44.5  ,  -89.5, -29.5  ,  -89.5, -47.5  ,  63, -48  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip50", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -70.5, 42.5  ,  -89.5, -29.5  ,  -39, 45  ,  -51, 50  ,  -65, 49  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip50", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   21.5, 44.5  ,  52, 45  ,  42.5, 49.5  ,  28, 50  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip50", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -8.5, 44.5  ,  -89.5, -29.5  ,  21.5, 44.5  ,  12, 50  ,  -2, 50  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip50", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   52, 45  ,  81, 45  ,  71, 50  ,  59, 50  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip50", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -39, 45  ,  -89.5, -29.5  ,  -8.5, 44.5  ,  -20, 50  ,  -32, 50  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip60"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip60", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   101.5, 37.5  ,  97.5, 44.5  ,  37.5, 44.5  ,  -104.5, -29.5  ,  -104.5, -47.5  ,  78, -49  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip60", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -85.5, 42.5  ,  -104.5, -29.5  ,  -54, 45  ,  -63.5, 49.5  ,  -78, 50  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip60", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   6.5, 44.5  ,  37.5, 44.5  ,  25, 50  ,  13, 50  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip60", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   67.5, 44.5  ,  97.5, 44.5  ,  88, 50  ,  74, 50  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip60", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37.5, 44.5  ,  67.5, 44.5  ,  58, 50  ,  44, 50  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip60", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -23.5, 44.5  ,  -104.5, -29.5  ,  6.5, 44.5  ,  -3, 50  ,  -17, 50  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip60", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -54, 45  ,  -104.5, -29.5  ,  -23.5, 44.5  ,  -35, 50  ,  -47, 50  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip60", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -104.5, -29.5  ,  37.5, 44.5  ,  6.5, 44.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip70"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip70", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -49, -48.5  ,  -71, 45.5  ,  -78, 49.5  ,  -93, 50.5  ,  -98, 47.5  ,  -115, -15.5  ,  -119, -48.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip70", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   117, 38.5  ,  114, 38.5  ,  -49, -48.5  ,  94, -48.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip70", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   89, 50.5  ,  83, 44.5  ,  114, 38.5  ,  110, 47.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip70", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -8, 44.5  ,  -49, -48.5  ,  20, 45.5  ,  13, 49.5  ,  -2, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip70", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -38, 44.5  ,  -49, -48.5  ,  -8, 44.5  ,  -17, 49.5  ,  -32, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip70", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   53, 44.5  ,  83, 44.5  ,  78, 48.5  ,  59, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip70", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -71, 45.5  ,  -49, -48.5  ,  -38, 44.5  ,  -48, 49.5  ,  -62, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip70", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   20, 45.5  ,  -49, -48.5  ,  53, 44.5  ,  48, 48.5  ,  29, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip70", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   53, 44.5  ,  -49, -48.5  ,  114, 38.5  ,  83, 44.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip80"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip80", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   123.5, 48.5  ,  104.5, 50.5  ,  95.5, 45.5  ,  129.5, 38.5  ,  128.5, 44.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip80", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   132.5, 38.5  ,  129.5, 38.5  ,  -134.5, -48.5  ,  108.5, -48.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip80", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   67.5, 44.5  ,  95.5, 45.5  ,  88.5, 49.5  ,  73.5, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip80", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37.5, 44.5  ,  67.5, 44.5  ,  58.5, 49.5  ,  43.5, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip80", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -23.5, 44.5  ,  4.5, 45.5  ,  -2.5, 49.5  ,  -17.5, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip80", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -53.5, 44.5  ,  -134.5, -48.5  ,  -23.5, 44.5  ,  -32.5, 49.5  ,  -47.5, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip80", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -86.5, 45.5  ,  -134.5, -48.5  ,  -53.5, 44.5  ,  -63.5, 49.5  ,  -77.5, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip80", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   4.5, 45.5  ,  -134.5, -48.5  ,  37.5, 44.5  ,  32.5, 48.5  ,  13.5, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip80", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -113.5, 47.5  ,  -130.5, -15.5  ,  -134.5, -48.5  ,  -86.5, 45.5  ,  -93.5, 49.5  ,  -108.5, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip80", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   67.5, 44.5  ,  -134.5, -48.5  ,  129.5, 38.5  ,  95.5, 45.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip80", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -134.5, -48.5  ,  4.5, 45.5  ,  -23.5, 44.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip80", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -134.5, -48.5  ,  67.5, 44.5  ,  37.5, 44.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip90"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip90", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   147.5, 38.5  ,  114.5, 44.5  ,  52.5, 44.5  ,  -47.5, -48.5  ,  124.5, -48.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip90", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -36.5, 44.5  ,  -47.5, -48.5  ,  -6.5, 43.5  ,  -17.5, 49.5  ,  -29.5, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip90", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   52.5, 44.5  ,  82.5, 44.5  ,  73.5, 49.5  ,  61.5, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip90", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -47.5, -48.5  ,  -68.5, 44.5  ,  -127.5, 46.5  ,  -145.5, -23.5  ,  -147.5, -48.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip90", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -97.5, 45.5  ,  -68.5, 44.5  ,  -77.5, 49.5  ,  -89.5, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip90", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   114.5, 44.5  ,  147.5, 38.5  ,  141.5, 46.5  ,  121.5, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip90", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   82.5, 44.5  ,  114.5, 44.5  ,  108.5, 48.5  ,  91.5, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip90", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -68.5, 44.5  ,  -47.5, -48.5  ,  -36.5, 44.5  ,  -42.5, 48.5  ,  -59.5, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip90", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -6.5, 43.5  ,  20.5, 45.5  ,  0.5, 50.5  ,  -6.5, 46.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip90", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   20.5, 45.5  ,  -47.5, -48.5  ,  52.5, 44.5  ,  43.5, 49.5  ,  31.5, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip90", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -124.5, 48.5  ,  -127.5, 46.5  ,  -97.5, 45.5  ,  -108.5, 49.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip90", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -6.5, 43.5  ,  -47.5, -48.5  ,  20.5, 45.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip100"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip100", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -57, 66.5  ,  -76, 48.5  ,  53, -67.5  ,  75, -56.5  ,  76, 67.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip100", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   53, -67.5  ,  -76, 48.5  ,  -76, -68.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip200"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip200", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -69.5, 38  ,  -80.5, 28  ,  68.5, -38  ,  80.5, -31  ,  80.5, 37  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip200", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   68.5, -38  ,  -80.5, 28  ,  -80.5, -38  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip300"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip300", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   18, 32  ,  -80, 23  ,  -80, -44  ,  68, -44  ,  81, -39  ,  80, 32  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip300", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -80, 23  ,  18, 32  ,  18, 44  ,  -56, 44  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip400"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip400", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -63.5, 43  ,  74.5, -30.5  ,  86.5, -25.5  ,  86.5, 43.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip400", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   61.5, -44  ,  74.5, -37.5  ,  74.5, -30.5  ,  -63.5, 43  ,  -87, 21.5  ,  -86.5, -44.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip500"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip500", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   24.5, 38.5  ,  74.5, -37.5  ,  86.5, -32.5  ,  86.5, 38.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip500", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   61.5, -50  ,  74.5, -42.5  ,  74.5, -37.5  ,  24.5, 38.5  ,  -51.5, 49  ,  -87, 15.5  ,  -86.5, -50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip500", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -51.5, 49  ,  24.5, 38.5  ,  24.5, 49.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip600"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip600", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -56, 49.5  ,  81, -24.5  ,  93, -19.5  ,  93, 49.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip600", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   55, -50  ,  81, -24.5  ,  -56, 49.5  ,  -93, 16  ,  -93, -49.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip600", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   81, -24.5  ,  68, -37.5  ,  80.5, -31.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip600", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   68, -37.5  ,  55, -50  ,  68, -43.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip700"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip700", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   32.5, 44  ,  80.5, -31  ,  92.5, -26  ,  92.5, 44  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip700", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   80.5, -31  ,  32.5, 44  ,  67.5, -43  ,  80.5, -39  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip700", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   67.5, -43  ,  32.5, 44  ,  -43.5, 56  ,  56.5, -56  ,  67.5, -51  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip700", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   56.5, -56  ,  -43.5, 56  ,  -91.5, 10  ,  -92.5, -56  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip700", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -43.5, 56  ,  32.5, 44  ,  33.5, 56  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip800"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip800", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -50, 56  ,  87, -20  ,  99, -15  ,  99, 56  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip800", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   61, -43  ,  -50, 56  ,  -99, 11  ,  50, -56  ,  61, -51  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip800", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   50, -56  ,  -99, 11  ,  -99, -56  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip800", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   74, -32  ,  -50, 56  ,  61, -43  ,  74, -39  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip800", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   87, -20  ,  -50, 56  ,  74, -32  ,  87, -27  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip900"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip900", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   39, 50  ,  87, -26  ,  99, -21  ,  99, 50  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip900", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   50, -62  ,  61, -57  ,  62, -50  ,  39, 50  ,  -38, 62  ,  -98, 4  ,  -99, -62  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip900", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   87, -26  ,  39, 50  ,  75, -38  ,  87, -33  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip900", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   75, -38  ,  39, 50  ,  62, -50  ,  74, -45  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip900", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -38, 62  ,  39, 50  ,  39, 62  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip1000"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip1000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -96.5, -1  ,  96.1666717529297, 49.6666669845581  ,  103.5, 62  ,  -103.5, 7  ,  -103.5, -1  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip1000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37.5, -62  ,  95.5, -10  ,  96.1666717529297, 49.6666669845581  ,  -96.5, -1  ,  -96.5, -62  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip1000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   103.5, 62  ,  96.1666717529297, 49.6666669845581  ,  103.16667175293, 54.6666665077209  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip1000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -103.5, 7  ,  103.5, 62  ,  -45.5, 62  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip2000"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip2000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -13.3905944824219, -19.7319450378418  ,  -5.5, -12.5  ,  6.30306243896484, 14.841356754303  ,  8.5, 21.5  ,  -43.5, 22.5  ,  -63.5, 4.5  ,  -61.5, -20.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip2000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   62.5, 17.5  ,  6.30306243896484, 14.841356754303  ,  -5.5, -12.5  ,  -4.8566780090332, -19.7319450378418  ,  40.5, -21  ,  61.5, -2.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip2000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   6.30306243896484, 14.841356754303  ,  62.5, 17.5  ,  63.5, 21.5  ,  12.5, 21.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip3000"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip3000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   63, 32.5  ,  -44.5, 32  ,  5.5, -9.5  ,  39.5, -10  ,  61, 8.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip3000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -60.5, -33  ,  -59.5, -33  ,  4.5, -15.5  ,  5.5, -9.5  ,  -44.5, 32  ,  -64, 12.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip3000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   4.5, -15.5  ,  -59.5, -33  ,  -17.5, -33  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip4000"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip4000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -43.5, 34  ,  -7.5, -26  ,  60.5, -15  ,  63.5, 33  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip4000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -15.5, -33  ,  -7.5, -26  ,  -43.5, 34  ,  -63.5, 15  ,  -63.5, -11  ,  -61.5, -32  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip4000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   60.5, -15  ,  -7.5, -26  ,  -4.5, -33  ,  42.5, -33  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip5000"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip5000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -15.5, -44.5  ,  3.5, -27.5  ,  5.5, -21.5  ,  -44.5, 44  ,  -64, 24  ,  -61.5, -44  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip5000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -44.5, 44  ,  5.5, -21.5  ,  43.5, -19.5  ,  60.5, -3.5  ,  63, 44  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip6000"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip6000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -15.5, -44  ,  -7.5, -37  ,  -43.5, 45.5  ,  -64, 24.5  ,  -62.5, -43.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip6000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -43.5, 45.5  ,  -7.5, -37  ,  60.5, -26  ,  63, 44.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip6000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   60.5, -26  ,  -7.5, -37  ,  -4.5, -44  ,  42.5, -43.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip7000"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip7000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -15.5, -55.5  ,  4.5, -36.5  ,  4.5, -32.5  ,  -43.5, 56.5  ,  -62.5, 39.5  ,  -62.5, -53.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip7000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -43.5, 56.5  ,  4.5, -32.5  ,  41.5, -32.5  ,  63.5, 5.5  ,  63.5, 56.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip7000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   63.5, 5.5  ,  41.5, -32.5  ,  61.5, -14.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip8000"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip8000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -43.5, 56  ,  -5.5, -48  ,  61.5, -37  ,  63.5, 56  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip8000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -15.5, -56  ,  -5.5, -48  ,  -43.5, 56  ,  -62.5, 39  ,  -62.5, -54  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip8000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   61.5, -37  ,  -5.5, -48  ,  -5.5, -55  ,  40.5, -56  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip9000"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip9000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -43.5, 67  ,  -62.5, 50  ,  4.5, -45  ,  61.5, -26  ,  63.5, -6  ,  63.5, 67  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip9000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -14.5, -67  ,  3.5, -51  ,  4.5, -45  ,  -62.5, 50  ,  -62.5, -65  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip9000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   61.5, -26  ,  4.5, -45  ,  40.5, -45  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip10000"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip10000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -38.5, 67  ,  -63.5, 37  ,  -63.5, -65  ,  24.5, -67  ,  63.5, -43  ,  63.5, 61  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip30000"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip30000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -72, 39.5  ,  -85.5, 25.5  ,  -86.5, -28.5  ,  72, -39.5  ,  85.5, -24.5  ,  85.5, 29.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip40000"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip40000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -35, -64.5  ,  -20, -50  ,  -19, -9.5  ,  -86.5, 47  ,  -86, -60  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip40000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -72, 65  ,  -86.5, 47  ,  73, -14.5  ,  86, -1  ,  86, 54  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip40000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   73, -14.5  ,  -86.5, 47  ,  -19, -9.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip50000"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip50000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   19, -64.5  ,  33.5, -51.5  ,  33.5, -11.5  ,  -73, 65  ,  -86.5, 48.5  ,  -87, -58.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip50000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -73, 65  ,  33.5, -11.5  ,  72, -14  ,  85.5, -0.5  ,  86, 56.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip60000"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip60000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -71, 68.5  ,  -86.5, 51.5  ,  71, -67  ,  86, -53.5  ,  86, 57.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip60000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   71, -67  ,  -86.5, 51.5  ,  -86.5, -56.5  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip70000"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip70000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -73, 95  ,  -85, 80  ,  73, -39  ,  86, -26  ,  86, 86  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip70000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -33, -88  ,  -20, -74  ,  -20, -33  ,  -85, 80  ,  -86, -85  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip70000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   73, -39  ,  -85, 80  ,  -20, -33  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip80000"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip80000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -73, 95  ,  -85, 80  ,  34, -37  ,  73, -39  ,  86, -26  ,  86, 86  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip80000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   20, -91  ,  33, -77  ,  34, -37  ,  -85, 80  ,  -86, -84  }
                    }
                    
                    
                    
		}
		
		, 
		["chocchip90000"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "chochip90000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   73, -95  ,  86, -82  ,  -73, 95  ,  -85, 80  ,  -86, -85  }
                    }
                     ,
                    {
                    pe_fixture_id = "chochip90000", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -73, 95  ,  86, -82  ,  86, 85  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

