--[[
Spriteloq metadata
Generated by SpriteLoq: Loqheart's Flash SWF to sprite sheet Corona SDK exporter (c) Loqheart 2011
version 1.4.8
target Corona SDK
extension lua
exportName conveyorSprite
exportPath file:///Users/Anneke/Documents/iPad%20Project/Cookie%20Factory
sheetSize 2048x2048
sources 1
name; url; referencePoint; startFrame; totalFrames; frameRate; topLeft; bottomRight; sourceRect; loopParam; includeReverse; rasterize
Conveyor Belt; ../BG/Conveyor Belt.swf; (x=0, y=0); 1; 80; 30; (x=-265, y=-22); (x=265, y=22); (x=-267, y=-24, w=534, h=48); 0; false; false
assetShapes 0
]]

local sheet = false
local setInfo = false
local msFactor = 500  -- This should be 1000 ms. Corona BUG: The frame rate is playing back at around half speed at 30fps.

local function newSpriteSet(_sheet, _name, _startFrame, _frameCount, _frameRate, _loopParam, _xReference, _yReference, _spriteSourceWidth, _spriteSourceHeight, _unscaledSpriteX, _unscaledSpriteY, _unscaledSpriteWidth, _unscaledSpriteHeight, _frames, _shapeOnly)
    if (_shapeOnly) then
        return
    end

    local set = sprite.newSpriteSet(_sheet, _startFrame, _frameCount)
    sprite.add(set, _name, 1, _frameCount, (_frameCount / _frameRate) * msFactor, _loopParam)
    setInfo[_name] = {set = set, xReference = _xReference, yReference = _yReference, spriteSourceSize = {width = _spriteSourceWidth, height = _spriteSourceHeight}, unscaledSpriteRect = {x = _unscaledSpriteX, y = _unscaledSpriteY, width = _unscaledSpriteWidth, height = _unscaledSpriteHeight}, frames = _frames, frameRate = _frameRate, frameCount = _frameCount, fpss = _frameRate / 1000, startFrame = _startFrame}
end

local function load()
    local frameSets = {}
    local allFrames = {}

    frameSets["Conveyor Belt"] = {
        {
            name="Conveyor Belt-1",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=720, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-2",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=0, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-3",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=48, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-4",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=48, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-5",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=96, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-6",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=96, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-7",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=144, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-8",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=144, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-9",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=192, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-10",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=192, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-11",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=240, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-12",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=240, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-13",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=288, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-14",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=288, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-15",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=336, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-16",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=336, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-17",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=384, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-18",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=384, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-19",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=432, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-20",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=432, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-21",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=480, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-22",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=480, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-23",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=528, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-24",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=528, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-25",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=576, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-26",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=576, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-27",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=624, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-28",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=624, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-29",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=672, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-30",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=672, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-31",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=672, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-32",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=672, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-33",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=672, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-34",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=672, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-35",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=672, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-36",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=672, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-37",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=672, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-38",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=672, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-39",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=672, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-40",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=720, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-41",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=0, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-42",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=768, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-43",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=768, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-44",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=816, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-45",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=816, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-46",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=864, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-47",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=864, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-48",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=912, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-49",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=912, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-50",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=960, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-51",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=960, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-52",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1008, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-53",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=1008, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-54",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1056, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-55",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=1056, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-56",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1104, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-57",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=1104, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-58",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1152, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-59",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=1152, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-60",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1200, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-61",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=1200, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-62",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1248, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-63",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=1248, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-64",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1296, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-65",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=1296, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-66",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1344, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-67",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=1344, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-68",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1392, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-69",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=1392, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-70",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1440, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-71",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1440, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-72",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1440, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-73",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1440, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-74",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1440, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-75",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1440, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-76",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1440, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-77",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1440, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-78",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1440, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-79",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1440, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        },
        {
            name="Conveyor Belt-80",
            spriteColorRect={x=0, y=0},
            textureRect={x=534, y=1440, width=534, height=48},
            spriteSourceSize={width=534, height=48},
            spriteTrimmed=false,
        }
    }
    allFrames = table.copy(allFrames, frameSets["Conveyor Belt"])


    sheet = sprite.newSpriteSheetFromData("conveyorSprite.png", {frames = allFrames })

    -- setInfo table contains info about sprites: { (spriteName = {set: set, xReference: xReference, yReference: yReference, spriteSourceSize = {width: width, height: height}})+ }
    setInfo = {}
    newSpriteSet(sheet, "Conveyor Belt", 1, 80, 30, 0, 0 - (534/2 + -267), 0 - (48/2 + -24), 534, 48, 0, 0, 534, 48, frameSets["Conveyor Belt"], false)

    local shapes = {}
    shapes["Conveyor Belt"] = {

    }

    return { sheet = sheet, setInfo = setInfo, shapes = shapes }
end

local function destroy()
    sheet:dispose()
    sheet = nil
    setInfo = nil
end

return { load = load, destroy = destroy }
