--[[
Spriteloq metadata
Generated by SpriteLoq: Loqheart's Flash SWF to sprite sheet Corona SDK exporter (c) Loqheart 2011
version 1.4.10
target Corona SDK
extension lua
exportName conveyorBelt
exportPath file:///Users/Anneke/Desktop
sheetSize 3297x3880
sources 1
name; url; referencePoint; startFrame; totalFrames; frameRate; topLeft; bottomRight; sourceRect; loopParam; includeReverse; rasterize
Conveyor@2; ../Documents/iPad Project/Conveyor@2.swf; (x=0, y=0); 1; 60; 30; (x=670, y=387); (x=1218, y=482); (x=668, y=385, w=552, h=99); 1; false; false
assetShapes 0
]]

local sheet = false
local setInfo = false
local msFactor = 500  -- This should be 1000 ms. Corona BUG: The frame rate is playing back at around half speed at 30fps.

local function newSpriteSet(_sheet, _name, _startFrame, _frameCount, _frameRate, _loopParam, _xReference, _yReference, _spriteSourceWidth, _spriteSourceHeight, _unscaledSpriteX, _unscaledSpriteY, _unscaledSpriteWidth, _unscaledSpriteHeight, _frames, _shapeOnly)
    if (_shapeOnly) then
        return
    end

    local set = sprite.newSpriteSet(_sheet, _startFrame, _frameCount)
    sprite.add(set, _name, 1, _frameCount, (_frameCount / _frameRate) * msFactor, _loopParam)
    setInfo[_name] = {set = set, xReference = _xReference, yReference = _yReference, spriteSourceSize = {width = _spriteSourceWidth, height = _spriteSourceHeight}, unscaledSpriteRect = {x = _unscaledSpriteX, y = _unscaledSpriteY, width = _unscaledSpriteWidth, height = _unscaledSpriteHeight}, frames = _frames, frameRate = _frameRate, frameCount = _frameCount, fpss = _frameRate / 1000, startFrame = _startFrame}
end

local function load()
    local frameSets = {}
    local allFrames = {}

    frameSets["Conveyor@2"] = {
        {
            name="Conveyor@2-1",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=990, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-2",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=0, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-3",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=0, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-4",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=99, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-5",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=99, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-6",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=99, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-7",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=198, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-8",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=198, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-9",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=198, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-10",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=297, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-11",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=297, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-12",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=297, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-13",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=396, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-14",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=396, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-15",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=396, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-16",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=495, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-17",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=495, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-18",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=495, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-19",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=594, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-20",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=594, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-21",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=594, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-22",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=693, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-23",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=693, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-24",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=693, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-25",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=792, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-26",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=792, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-27",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=792, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-28",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=891, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-29",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=891, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-30",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=891, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-31",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=0, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-32",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=990, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-33",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=990, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-34",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1089, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-35",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=1089, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-36",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=1089, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-37",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1188, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-38",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=1188, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-39",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=1188, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-40",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1287, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-41",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=1287, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-42",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=1287, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-43",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1386, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-44",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=1386, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-45",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=1386, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-46",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1485, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-47",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=1485, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-48",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=1485, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-49",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1584, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-50",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=1584, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-51",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=1584, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-52",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1683, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-53",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1782, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-54",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=1881, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-55",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=1683, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-56",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=1683, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-57",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=1782, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-58",
            spriteColorRect={x=0, y=0},
            textureRect={x=552, y=1881, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-59",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=1782, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        },
        {
            name="Conveyor@2-60",
            spriteColorRect={x=0, y=0},
            textureRect={x=1104, y=1881, width=552, height=99},
            spriteSourceSize={width=552, height=99},
            spriteTrimmed=false,
        }
    }
    allFrames = table.copy(allFrames, frameSets["Conveyor@2"])


    sheet = sprite.newSpriteSheetFromData("conveyorBelt.png", {frames = allFrames })

    -- setInfo table contains info about sprites: { (spriteName = {set: set, xReference: xReference, yReference: yReference, spriteSourceSize = {width: width, height: height}})+ }
    setInfo = {}
    newSpriteSet(sheet, "Conveyor@2", 1, 60, 30, 1, 0 - (552/2 + 668), 0 - (99/2 + 385), 552, 99, 0, 0, 552, 99, frameSets["Conveyor@2"], false)

    local shapes = {}
    shapes["Conveyor@2"] = {

    }

    return { sheet = sheet, setInfo = setInfo, shapes = shapes }
end

local function destroy()
    sheet:dispose()
    sheet = nil
    setInfo = nil
end

return { load = load, destroy = destroy }
