--[[
Spriteloq metadata
Generated by SpriteLoq: Loqheart's Flash SWF to sprite sheet Corona SDK exporter (c) Loqheart 2011
version 1.4.10
target Corona SDK
extension lua
exportName truckSprite3@0_5
exportPath file:///Users/Anneke/Desktop
sheetSize 512x256
sources 1
name; url; referencePoint; startFrame; totalFrames; frameRate; topLeft; bottomRight; sourceRect; loopParam; includeReverse; rasterize
TruckOpening; ../Documents/iPad Project/TruckOpening.swf; (x=0, y=0); 61; 30; 30; (x=-154, y=-100); (x=154, y=94); (x=-156, y=-102, w=312, h=198); 1; false; false
assetShapes 0
]]

local sheet = false
local setInfo = false
local msFactor = 500  -- This should be 1000 ms. Corona BUG: The frame rate is playing back at around half speed at 30fps.

local function newSpriteSet(_sheet, _name, _startFrame, _frameCount, _frameRate, _loopParam, _xReference, _yReference, _spriteSourceWidth, _spriteSourceHeight, _unscaledSpriteX, _unscaledSpriteY, _unscaledSpriteWidth, _unscaledSpriteHeight, _frames, _shapeOnly)
    if (_shapeOnly) then
        return
    end

    local set = sprite.newSpriteSet(_sheet, _startFrame, _frameCount)
    sprite.add(set, _name, 1, _frameCount, (_frameCount / _frameRate) * msFactor, _loopParam)
    setInfo[_name] = {set = set, xReference = _xReference, yReference = _yReference, spriteSourceSize = {width = _spriteSourceWidth, height = _spriteSourceHeight}, unscaledSpriteRect = {x = _unscaledSpriteX, y = _unscaledSpriteY, width = _unscaledSpriteWidth, height = _unscaledSpriteHeight}, frames = _frames, frameRate = _frameRate, frameCount = _frameCount, fpss = _frameRate / 1000, startFrame = _startFrame}
end

local function load()
    local frameSets = {}
    local allFrames = {}

    frameSets["TruckOpening"] = {
        {
            name="TruckOpening-1",
            spriteColorRect={x=0, y=1},
            textureRect={x=316, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-2",
            spriteColorRect={x=0, y=1},
            textureRect={x=316, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-3",
            spriteColorRect={x=0, y=1},
            textureRect={x=316, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-4",
            spriteColorRect={x=0, y=1},
            textureRect={x=316, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-5",
            spriteColorRect={x=0, y=1},
            textureRect={x=316, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-6",
            spriteColorRect={x=0, y=1},
            textureRect={x=316, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-7",
            spriteColorRect={x=0, y=1},
            textureRect={x=316, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-8",
            spriteColorRect={x=0, y=1},
            textureRect={x=316, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-9",
            spriteColorRect={x=0, y=1},
            textureRect={x=316, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-10",
            spriteColorRect={x=0, y=1},
            textureRect={x=158, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-11",
            spriteColorRect={x=0, y=1},
            textureRect={x=158, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-12",
            spriteColorRect={x=0, y=1},
            textureRect={x=158, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-13",
            spriteColorRect={x=0, y=1},
            textureRect={x=158, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-14",
            spriteColorRect={x=0, y=1},
            textureRect={x=158, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-15",
            spriteColorRect={x=0, y=1},
            textureRect={x=158, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-16",
            spriteColorRect={x=0, y=1},
            textureRect={x=158, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-17",
            spriteColorRect={x=0, y=1},
            textureRect={x=158, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-18",
            spriteColorRect={x=0, y=1},
            textureRect={x=158, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-19",
            spriteColorRect={x=0, y=1},
            textureRect={x=158, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-20",
            spriteColorRect={x=0, y=1},
            textureRect={x=0, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-21",
            spriteColorRect={x=0, y=1},
            textureRect={x=0, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-22",
            spriteColorRect={x=0, y=1},
            textureRect={x=0, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-23",
            spriteColorRect={x=0, y=1},
            textureRect={x=0, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-24",
            spriteColorRect={x=0, y=1},
            textureRect={x=0, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-25",
            spriteColorRect={x=0, y=1},
            textureRect={x=0, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-26",
            spriteColorRect={x=0, y=1},
            textureRect={x=0, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-27",
            spriteColorRect={x=0, y=1},
            textureRect={x=0, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-28",
            spriteColorRect={x=0, y=1},
            textureRect={x=0, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-29",
            spriteColorRect={x=0, y=1},
            textureRect={x=0, y=0, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        },
        {
            name="TruckOpening-30",
            spriteColorRect={x=0, y=1},
            textureRect={x=0, y=100, width=158, height=100},
            spriteSourceSize={width=158, height=101},
            spriteTrimmed=true,
        }
    }
    allFrames = table.copy(allFrames, frameSets["TruckOpening"])


    sheet = sprite.newSpriteSheetFromData("truckSprite3@0_5.png", {frames = allFrames })

    -- setInfo table contains info about sprites: { (spriteName = {set: set, xReference: xReference, yReference: yReference, spriteSourceSize = {width: width, height: height}})+ }
    setInfo = {}
    newSpriteSet(sheet, "TruckOpening", 1, 30, 30, 1, 0 - (158/2 + -79), 0 - (101/2 + -52), 158, 101, 0, 2, 312, 195, frameSets["TruckOpening"], false)

    local shapes = {}
    shapes["TruckOpening"] = {

    }

    return { sheet = sheet, setInfo = setInfo, shapes = shapes }
end

local function destroy()
    sheet:dispose()
    sheet = nil
    setInfo = nil
end

return { load = load, destroy = destroy }
